# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHqZepEp6ZEe92FIV-nMaYKAx0REdjnU
"""

import streamlit as st
import pandas as pd
import plotly.express as px

df = pd.read_csv("IPUMS.csv")
occ = pd.read_csv("Occupation_Codes.csv")
occ["OCC Code"] = pd.to_numeric(occ["OCC Code"], errors="coerce")
df = df.merge(occ, left_on="OCC", right_on="OCC Code", how="left")
df = df.drop(columns=["YEAR", "STATEFIP", "OCC Code", "CITIZEN", "Unnamed: 3"], errors="ignore")
df = df[(df["UHRSWORKT"] >= 35) & (df["UHRSWORKT"] < 999) & (df["INCWAGE"] > 0)].copy()
df = df.dropna(subset=["Major Category"])

st.title("Career Earnings and Work-Life Analysis")
st.write("Authors: Tree Miles, Rayna Kossoy, Elodia")
st.sidebar.header("Filters")
selected_category = st.sidebar.multiselect("Select Major Category:", df["Major Category"].unique(), default=list(df["Major Category"].unique()))
df_filtered = df[df["Major Category"].isin(selected_category)]

income_by_cat = df_filtered.groupby("Major Category")["INCWAGE"].mean().reset_index().sort_values("INCWAGE", ascending=True)
income_by_cat.columns = ["Major Category", "Mean Income ($)"]
fig = px.bar(income_by_cat, x="Mean Income ($)", y="Major Category", orientation="h", title="Average Annual Income by Major Category")
st.plotly_chart(fig)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# plotly